on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer-cmd: buildozer -v init

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./buildozer.spec
